// Embedded Postgres integration checks. Auth/Storage schemas below are explicit
// test stubs; this does not deploy or verify a live Supabase project.
import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';

const db = new PGlite();
const OWNER = '11111111-1111-4111-8111-111111111111';
const OTHER = '22222222-2222-4222-8222-222222222222';
const STUDENT = '33333333-3333-4333-8333-333333333333';
const SESSION = '44444444-4444-4444-8444-444444444444';
const INVOICE = '55555555-5555-4555-8555-555555555555';
const ITEM = '66666666-6666-4666-8666-666666666666';
const PAYMENT = '77777777-7777-4777-8777-777777777777';
const now = '2026-10-01T10:00:00Z';
await db.exec(`
  create role anon; create role authenticated;
  create schema auth; create schema storage;
  grant usage on schema auth, storage, public to authenticated, anon;
  create table auth.users(id uuid primary key);
  insert into auth.users values('${OWNER}'),('${OTHER}');
  create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid primary key,bucket_id text,name text);
  create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(regexp_replace(name,'/[^/]+$',''),'/') $$;
  alter table storage.objects enable row level security;
  grant all on storage.objects to authenticated,anon;
`);
await db.exec(await readFile(new URL('../migrations/202610010001_tutorspace.sql', import.meta.url), 'utf8'));
console.log('PASS SQL migration compiled and ran with Supabase auth/storage stubs');
await db.query('insert into public.workspace_owner(singleton,user_id) values(true,$1)',[OWNER]);
async function asUser(user, role = 'authenticated') { await db.exec(`reset role; set role ${role};`); await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]); }
async function load() { return (await db.query('select public.workspace_load() as result')).rows[0].result; }
async function save(data, revision, allow = false) { return (await db.query('select public.workspace_save($1::jsonb,$2::bigint,$3::boolean) as result',[JSON.stringify(data),revision,allow])).rows[0].result; }
async function rejects(fn, expected) { await assert.rejects(fn, expected); }
await asUser(OWNER);
const initial = await load(); assert.equal(initial.revision,0); assert.equal(initial.data.demo,false); assert.equal(initial.data.students.length,0);
console.log('PASS Cloud owner starts with an empty non-demo workspace');
const data = structuredClone(initial.data);
data.profile.name = 'Gia sư kiểm thử';
data.students.push({id:STUDENT,name:'Học sinh kiểm thử',grade:'Lớp 9',subject:'Toán',parentName:'',parentPhone:'',startDate:'2026-09-01',mode:'online',rateType:'hour',rate:180000,color:'#4F7CFF',avatar:'',status:'active',notes:'',goals:'',createdAt:now,updatedAt:now});
data.sessions.push({id:SESSION,studentId:STUDENT,scheduleId:null,date:'2026-09-05',startTime:'18:00',endTime:'19:30',subject:'Toán',mode:'online',location:'',notes:'',status:'completed',actualMinutes:90,billable:null,rate:180000,rateType:'hour',lessonNote:{content:'Luyện tập',attitude:'',understanding:'',homework:'',nextPlan:''},createdAt:now,updatedAt:now});
data.invoices.push({id:INVOICE,studentId:STUDENT,code:'TS-202609-1',month:'2026-09',status:'issued',items:[{id:ITEM,sessionId:SESSION,date:'2026-09-05',minutes:90,rate:180000,rateType:'hour',amount:270000,description:'Toán'}],surcharge:0,discount:0,adjustmentNote:'',comment:'Nhận xét',snapshot:{studentName:'Học sinh kiểm thử',grade:'Lớp 9',subject:'Toán',tutorName:'Gia sư kiểm thử',brand:'TutorSpace',bankName:'',bankAccount:'',bankHolder:'',qrImage:''},createdAt:now,updatedAt:now,issuedAt:now});
data.payments.push({id:PAYMENT,invoiceId:INVOICE,amount:100000,date:'2026-10-01',note:'Đợt 1',createdAt:now});
assert.equal(await save(data,0),1);
const first = await load(); assert.equal(first.revision,1); assert.equal(first.data.sessions[0].lessonNote.content,'Luyện tập'); assert.equal(first.data.invoices[0].items[0].amount,270000);
console.log('PASS Normalized student/session/note/invoice/item/payment save and load');
const next = structuredClone(first.data); next.students[0].rate = 240000; next.sessions[0].rate=240000; next.settings.bankHolder='Người mới';
assert.equal(await save(next,1),2); assert.equal((await load()).data.invoices[0].items[0].rate,180000);
console.log('PASS Historical snapshots survive source/rate/settings edits');
await rejects(() => save(first.data,1),/VERSION_CONFLICT/); assert.equal((await load()).revision,2);
console.log('PASS Stale revision rejected without overwriting newer data');
const changed = structuredClone((await load()).data); changed.invoices[0].comment='Sửa âm thầm';
await rejects(() => save(changed,2),/ISSUED_IMMUTABLE/); assert.equal((await load()).data.invoices[0].comment,'Nhận xét');
assert.equal(await save(changed,2,true),3);
console.log('PASS Issued content rejects silent edits; explicit correction succeeds');
const paidTooMuch = structuredClone((await load()).data); paidTooMuch.payments[0].amount=270001;
await rejects(() => save(paidTooMuch,3),/OVERPAYMENT/); assert.equal((await load()).data.payments[0].amount,100000); assert.equal((await load()).revision,3);
console.log('PASS Overpayment rejected and entire transaction rolled back');
const duplicate = structuredClone((await load()).data); duplicate.invoices.push({...duplicate.invoices[0],id:'88888888-8888-4888-8888-888888888888',month:'2026-10',items:duplicate.invoices[0].items.map(i=>({...i,id:'99999999-9999-4999-8999-999999999999'}))});
await rejects(() => save(duplicate,3),/session_billed_once/);
duplicate.invoices[1].month='2026-09'; await rejects(() => save(duplicate,3),/one_issued_invoice_per_month/);
console.log('PASS Duplicate billed lesson and duplicate issued student/month rejected');
const draft = structuredClone((await load()).data); draft.invoices[0].status='draft'; draft.invoices[0].issuedAt=null;
await rejects(() => save(draft,3,true),/DRAFT_PAYMENT/);
console.log('PASS Draft invoices cannot receive payments');

const image = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+NMhQAAAAASUVORK5CYII=';
const secondImage = `${image.slice(0,-4)}AAAA`; // Different bytes, same recognized PNG header.
const hashImage = uri => createHash('sha256').update(uri,'utf8').digest('hex');
const key = hashImage(image); const secondKey = hashImage(secondImage);
const withImages = structuredClone((await load()).data);
withImages.assets = {[key]:image};
withImages.profile.avatar=`asset:${key}`; withImages.settings.qrImage=`asset:${key}`;
withImages.students[0].avatar=`asset:${key}`; withImages.invoices[0].snapshot.qrImage=`asset:${key}`;
assert.equal(await save(withImages,3,true),4);
const assetRoundtrip = await load();
assert.deepEqual(assetRoundtrip.data.assets,{[key]:image});
assert.equal(assetRoundtrip.data.profile.avatar,`asset:${key}`);
assert.equal(assetRoundtrip.data.invoices[0].snapshot.qrImage,`asset:${key}`);
assert.equal((await db.query('select count(*)::integer as total from public.image_assets')).rows[0].total,1);
assert.equal((await db.query('select snapshot from public.invoices')).rows[0].snapshot.qrImage,`asset:${key}`);
console.log('PASS Repeated avatar/settings/issued-QR bytes intern once and round-trip in one asset dictionary');
const noAssetPayload = structuredClone(assetRoundtrip.data); noAssetPayload.assets = {}; noAssetPayload.settings.bankHolder='Nội dung mới';
assert.equal(await save(noAssetPayload,4),5);
assert.deepEqual((await load()).data.assets,{[key]:image});
console.log('PASS References resolve against existing private assets without resending image bytes');
const missing = structuredClone((await load()).data); missing.profile.avatar=`asset:${'a'.repeat(64)}`;
await rejects(()=>save(missing,5),/ASSET_REFERENCE_MISSING/);
const remote = structuredClone((await load()).data); remote.settings.qrImage='https://example.com/qr.png';
await rejects(()=>save(remote,5),/ASSET_REFERENCE_INVALID/);
remote.settings.qrImage='asset:../other-owner'; await rejects(()=>save(remote,5),/ASSET_REFERENCE_INVALID/);
const malformed = structuredClone((await load()).data); malformed.assets[key]='data:image/png;base64,YWJjZA==';
await rejects(()=>save(malformed,5),/ASSET_IMMUTABLE/);
const mismatched = structuredClone((await load()).data); mismatched.assets['b'.repeat(64)]=secondImage;
await rejects(()=>save(mismatched,5),/ASSET_HASH_MISMATCH/);
const badHeader = structuredClone((await load()).data); const fake='data:image/png;base64,YWJjZA=='; badHeader.assets[hashImage(fake)]=fake;
await rejects(()=>save(badHeader,5),/ASSET_INVALID/);
const oversized = structuredClone((await load()).data); const bigBytes=Buffer.alloc(2097153); Buffer.from('89504e470d0a1a0a','hex').copy(bigBytes); const bigImage=`data:image/png;base64,${bigBytes.toString('base64')}`;
oversized.assets[hashImage(bigImage)]=bigImage; await rejects(()=>save(oversized,5),/ASSET_TOO_LARGE/);
assert.equal((await load()).revision,5); assert.equal((await db.query('select count(*)::integer as total from public.image_assets')).rows[0].total,1);
console.log('PASS Missing/remote/malformed/incorrect-hash/oversized images rejected with transaction rollback');
const swappedSnapshot = structuredClone((await load()).data); swappedSnapshot.assets[secondKey]=secondImage; swappedSnapshot.invoices[0].snapshot.qrImage=`asset:${secondKey}`;
await rejects(()=>save(swappedSnapshot,5),/ISSUED_IMMUTABLE/);
const settingsReplaced = structuredClone((await load()).data); settingsReplaced.assets[secondKey]=secondImage; settingsReplaced.settings.qrImage=`asset:${secondKey}`; settingsReplaced.profile.avatar=''; settingsReplaced.students[0].avatar='';
assert.equal(await save(settingsReplaced,5),6);
const imageHistory = await load(); assert.equal(imageHistory.data.invoices[0].snapshot.qrImage,`asset:${key}`); assert.equal(imageHistory.data.settings.qrImage,`asset:${secondKey}`); assert.equal(Object.keys(imageHistory.data.assets).length,2);
console.log('PASS Replacing current QR preserves old immutable invoice bytes and snapshot reference');
const rollAssetsBack = structuredClone(imageHistory.data); const thirdImage=`${image.slice(0,-4)}AAAB`; const thirdKey=hashImage(thirdImage); rollAssetsBack.assets[thirdKey]=thirdImage; rollAssetsBack.profile.avatar=`asset:${thirdKey}`; rollAssetsBack.payments[0].amount=270001;
await rejects(()=>save(rollAssetsBack,6),/OVERPAYMENT/); assert.equal((await db.query('select count(*)::integer as total from public.image_assets')).rows[0].total,2);
console.log('PASS Failed financial writes also roll back newly interned assets');
await db.exec('reset role;');
const foreignImage = `${image.slice(0,-4)}AAAC`; const foreignKey = hashImage(foreignImage);
await db.query('insert into public.image_assets(owner_id,asset_key,data_uri) values($1,$2,$3)',[OTHER,foreignKey,foreignImage]);
await asUser(OWNER);
const foreignReference=structuredClone((await load()).data); foreignReference.profile.avatar=`asset:${foreignKey}`;
await rejects(()=>save(foreignReference,6),/ASSET_REFERENCE_MISSING/); assert.equal((await db.query('select count(*)::integer as total from public.image_assets')).rows[0].total,2);
assert.equal(Object.keys((await load()).data.assets).length,2);
await rejects(()=>db.query('update public.image_assets set data_uri=$1 where asset_key=$2',[secondImage,key]),/permission denied/);
console.log('PASS Assets cannot resolve across owner boundaries or be mutated through table APIs');
await db.query("insert into storage.objects(id,bucket_id,name) values($1,'tutorspace-private',$2)",[ITEM,`${OWNER}/qr.png`]);
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await asUser(OTHER);
await rejects(load,/OWNER_ONLY/); await rejects(()=>save(data,0),/OWNER_ONLY/);
assert.equal((await db.query('select * from public.students')).rows.length,0); assert.equal((await db.query('select * from public.invoices')).rows.length,0); assert.equal((await db.query('select * from storage.objects')).rows.length,0);
assert.equal((await db.query('select * from public.image_assets where owner_id=$1',[OWNER])).rows.length,0);
await rejects(()=>db.query("insert into storage.objects(id,bucket_id,name) values($1,'tutorspace-private',$2)",[INVOICE,`${OTHER}/qr.png`]),/row-level security/);
console.log('PASS Non-owner RPC/read/upload blocked by ownership and RLS');
await asUser('', 'anon'); await rejects(load,/permission denied/); await rejects(()=>db.query('select * from public.students'),/permission denied/);
console.log('PASS Anonymous RPC and table reads denied');
await asUser(OWNER);
const emptied=structuredClone(initial.data);
await rejects(()=>save(emptied,6),/ISSUED_IMMUTABLE/); assert.equal(await save(emptied,6,true),7); assert.equal((await load()).data.students.length,0);
assert.equal((await db.query('select count(*)::integer as total from public.image_assets')).rows[0].total,0); assert.deepEqual((await load()).data.assets,{});
console.log('PASS Confirmed reset is transactional; unconfirmed issued deletion denied');
await db.close();
