import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Plus, Search, LayoutGrid, List, Pencil, Phone, Video, MapPin, Clock3, ChevronRight, BookOpen, Target, CalendarDays, Mail } from 'lucide-react';
import { useWorkspace } from '../store';
import { today, money, formatDate, sessionMinutes, sessionCharge, invoiceTotal, invoicePaid, invoiceRemaining, invoiceStatus } from '../domain';
import type { Student, TeachingSession, LessonNote } from '../types';
import { weekdays } from '../calendar';
import { Avatar, Button, EmptyState, Field, Modal, PageHeading, StatusBadge, Tabs } from '../components/ui';
import StudentForm from '../components/StudentForm';
import SessionForm from '../components/SessionForm';
import { SessionDetail } from './Calendar';
import '../core.css';

export function StudentDetail({student,onClose}:{student:Student;onClose:()=>void}) {
  const {data,update,saving}=useWorkspace();const current=data.students.find(s=>s.id===student.id)||student;const [tab,setTab]=useState('overview');const [editing,setEditing]=useState(false);const [adding,setAdding]=useState(false);const [chosen,setChosen]=useState<TeachingSession|null>(null);const [goals,setGoals]=useState(current.goals);const [notes,setNotes]=useState(current.notes);useEffect(()=>{setGoals(current.goals);setNotes(current.notes);},[current.id,current.goals,current.notes]);
  const sessions=data.sessions.filter(s=>s.studentId===current.id).sort((a,b)=>(b.date+b.startTime).localeCompare(a.date+a.startTime));const completed=sessions.filter(s=>s.status==='completed');const schedules=data.schedules.filter(s=>s.studentId===current.id);const invoices=data.invoices.filter(i=>i.studentId===current.id).sort((a,b)=>b.month.localeCompare(a.month));const issued=invoices.filter(i=>i.status==='issued');const received=issued.reduce((sum,i)=>sum+invoicePaid(i,data.payments),0);const owed=issued.reduce((sum,i)=>sum+invoiceRemaining(i,data.payments),0);const accrued=sessions.reduce((sum,s)=>sum+sessionCharge(s),0);
  const lessons=(<div className="table-wrap"><table className="data-table"><thead><tr><th>Buổi học</th><th>Thời lượng</th><th>Nội dung / ghi chú</th><th>Trạng thái</th><th/></tr></thead><tbody>{sessions.map(s=><tr key={s.id}><td><strong>{formatDate(s.date)}</strong><small className="table-subtext">{s.startTime}–{s.endTime} · {s.subject}</small></td><td>{sessionMinutes(s)} phút</td><td className="lesson-summary">{s.lessonNote.content||s.notes||'Chưa có ghi chú'}</td><td><StatusBadge status={s.status}/></td><td><Button variant="ghost" aria-label={`Xem buổi học ngày ${formatDate(s.date)}`} onClick={()=>setChosen(s)}>Xem <ChevronRight size={14}/></Button></td></tr>)}</tbody></table></div>);
  return <><Modal open={!editing&&!adding&&!chosen} onClose={onClose} title="Hồ sơ học sinh" wide><div className="student-detail-top"><Avatar student={current} size="large"/><div><h2>{current.name}</h2><p>{current.grade} · {current.subject}</p><StatusBadge status={current.status}/></div><Button onClick={()=>setEditing(true)}><Pencil size={16}/>Chỉnh sửa</Button></div><Tabs value={tab} onChange={setTab} items={[{value:'overview',label:'Tổng quan'},{value:'history',label:'Lịch sử học tập'},{value:'notes',label:'Nhật ký & tiến độ'},{value:'fees',label:'Học phí'}]}>
    <div className="student-tab-body" >
    {tab==='overview'&&<><div className="student-detail-stats"><div><span>Buổi đã hoàn thành</span><strong>{completed.length}</strong></div><div><span>Tổng thời gian học</span><strong>{(completed.reduce((sum,s)=>sum+sessionMinutes(s),0)/60).toLocaleString('vi-VN',{maximumFractionDigits:1})} <small>giờ</small></strong></div><div><span>Đơn giá hiện tại</span><strong>{money(current.rate)}<small>/{current.rateType==='hour'?'giờ':'buổi'}</small></strong></div></div><div className="student-detail-columns"><section><h3 className="section-title">Thông tin học sinh</h3><dl className="profile-facts"><div><dt>Ngày bắt đầu</dt><dd>{formatDate(current.startDate)}</dd></div><div><dt>Hình thức</dt><dd>{current.mode==='online'?'Trực tuyến':'Trực tiếp'}</dd></div><div><dt>Phụ huynh</dt><dd>{current.parentName||'Chưa cập nhật'}</dd></div><div><dt>Điện thoại</dt><dd>{current.parentPhone?<a href={`tel:${current.parentPhone}`}><Phone size={14}/>{current.parentPhone}</a>:'Chưa cập nhật'}</dd></div></dl>{current.goals&&<div className="student-goal-box"><Target size={18}/><div><h4>Mục tiêu học tập</h4><p>{current.goals}</p></div></div>}</section><section><div className="section-title-row"><h3 className="section-title">Lịch học cố định</h3><Button variant="ghost" onClick={()=>setAdding(true)}><Plus size={15}/>Thêm</Button></div>{schedules.length?schedules.map(schedule=><div className="student-schedule" key={schedule.id}><div><CalendarDays size={17}/><strong>{[1,2,3,4,5,6,0].filter(day=>schedule.weekdays.includes(day)).map(day=>weekdays[day]).join(' · ')}</strong></div><p>{schedule.startTime}–{schedule.endTime} · {schedule.subject}</p><small className="muted">{formatDate(schedule.startDate)} – {formatDate(schedule.endDate)}</small>{schedule.endDate<today()&&<StatusBadge status="ended" label="Chu kỳ đã kết thúc"/>}</div>):<div className="compact-empty">Chưa có lịch cố định. Thêm lịch dạy và chọn lặp lại hàng tuần.</div>}<Button onClick={()=>setAdding(true)}><Plus size={16}/>Tạo lịch cho học sinh</Button></section></div>{current.notes&&<div className="student-private-notes"><h3>Ghi chú cá nhân</h3><p>{current.notes}</p></div>}</>}
    {tab==='history'&&(sessions.length?lessons:<EmptyState title="Chưa có buổi học" description="Lịch sử học tập sẽ xuất hiện khi bạn thêm lịch dạy." action={<Button onClick={()=>setAdding(true)}>Thêm lịch dạy</Button>}/>)}
    {tab==='notes'&&<><div className="progress-editor"><Field label="Mục tiêu học tập"><textarea rows={3} maxLength={5000} value={goals} onChange={e=>setGoals(e.target.value)} placeholder="Điều học sinh muốn đạt được..."/></Field><Field label="Vấn đề cần cải thiện / ghi chú cá nhân"><textarea rows={3} maxLength={10000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Điểm mạnh, điểm cần củng cố và điều cần lưu ý..."/></Field><Button variant="primary" loading={saving} disabled={goals===current.goals&&notes===current.notes} onClick={()=>void update(d=>({...d,students:d.students.map(s=>s.id===current.id?{...s,goals,notes,updatedAt:new Date().toISOString()}:s)}),'Đã lưu mục tiêu và ghi chú')}>Lưu tiến độ</Button></div><h3 className="section-title">Nhật ký từng buổi học</h3>{completed.some(s=>Object.values(s.lessonNote).some(Boolean))?<div className="student-journal">{completed.filter(s=>Object.values(s.lessonNote).some(Boolean)).map(s=><article className="journal-entry" key={s.id}><div className="journal-entry-heading"><span><BookOpen size={16}/><strong>{formatDate(s.date)}</strong> · {s.subject}</span><Button variant="ghost" onClick={()=>setChosen(s)}>Xem / sửa</Button></div>{([['content','Nội dung'],['attitude','Thái độ'],['understanding','Tiếp thu'],['homework','Bài tập'],['nextPlan','Buổi tiếp theo']] as [keyof LessonNote,string][]).map(([key,label])=>s.lessonNote[key]&&<p key={key}><strong>{label}: </strong>{s.lessonNote[key]}</p>)}</article>)}</div>:<EmptyState title="Nhật ký đang chờ những dòng đầu tiên" description="Thêm nhận xét khi hoàn thành buổi học để theo dõi tiến bộ của học sinh."/>}</>}
    {tab==='fees'&&<><div className="student-detail-stats"><div><span>Học phí phát sinh</span><strong>{money(accrued)}</strong></div><div><span>Đã nhận</span><strong className="success-text">{money(received)}</strong></div><div><span>Công nợ hóa đơn</span><strong className={owed?'warning-text':''}>{money(owed)}</strong></div></div><p className="form-hint">Học phí phát sinh dựa trên các buổi có tính phí. Công nợ chỉ gồm hóa đơn đã phát hành.</p><div className="section-title-row"><h3 className="section-title">Lịch sử hóa đơn</h3><Link className="btn btn-secondary" to={`/invoices?new=1&studentId=${current.id}`}><Plus size={16}/>Tạo hóa đơn</Link></div>{invoices.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Hóa đơn</th><th>Tổng học phí</th><th>Đã nhận</th><th>Còn lại</th><th>Trạng thái</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><Link to={`/invoices?invoice=${i.id}`}><strong>{i.code}</strong></Link><small className="table-subtext">Tháng {Number(i.month.slice(5))}/{i.month.slice(0,4)}</small></td><td>{money(invoiceTotal(i))}</td><td>{money(invoicePaid(i,data.payments))}</td><td>{i.status==='draft'?'—':money(invoiceRemaining(i,data.payments))}</td><td><StatusBadge status={invoiceStatus(i,data.payments)}/></td></tr>)}</tbody></table></div>:<EmptyState title="Chưa có hóa đơn" description="Tạo hóa đơn cuối tháng từ các buổi học thực tế."/>}</>}
    </div></Tabs></Modal><StudentForm open={editing} onClose={()=>setEditing(false)} student={current}/><SessionForm open={adding} onClose={()=>setAdding(false)} initialStudentId={current.id}/>{chosen&&<SessionDetail session={chosen} onClose={()=>setChosen(null)}/>}</>;
}

export default function Students(){const {data}=useWorkspace();const {id}=useParams();const navigate=useNavigate();const [params,setParams]=useSearchParams();const externalQuery=params.get('q')||'';const requestNew=params.get('new')==='1';const [query,setQuery]=useState(externalQuery);const [status,setStatus]=useState('all');const [view,setView]=useState<'cards'|'table'>('cards');const [adding,setAdding]=useState(requestNew);const [editing,setEditing]=useState<Student|undefined>();useEffect(()=>setQuery(externalQuery),[externalQuery]);useEffect(()=>{if(requestNew)setAdding(true);},[requestNew]);const selected=data.students.find(s=>s.id===id);const students=useMemo(()=>data.students.filter(s=>(status==='all'||s.status===status)&&`${s.name} ${s.grade} ${s.subject}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase())),[data.students,status,query]);
  const completedCount=(studentId:string)=>data.sessions.filter(s=>s.studentId===studentId&&s.status==='completed').length;const nextSession=(studentId:string)=>data.sessions.filter(s=>s.studentId===studentId&&s.date>=today()&&['scheduled','rescheduled'].includes(s.status)).sort((a,b)=>(a.date+a.startTime).localeCompare(b.date+b.startTime))[0];
  return <><PageHeading eyebrow="ĐỒNG HÀNH CÙNG HỌC SINH" title="Học sinh" description="Một góc nhìn đầy đủ về từng hành trình học tập." actions={<Button variant="primary" onClick={()=>setAdding(true)}><Plus size={18}/>Thêm học sinh</Button>}/><div className="student-status-summary">{[{value:'all',label:'Tất cả học sinh',count:data.students.length},{value:'active',label:'Đang học',count:data.students.filter(s=>s.status==='active').length},{value:'paused',label:'Tạm nghỉ',count:data.students.filter(s=>s.status==='paused').length},{value:'ended',label:'Đã kết thúc',count:data.students.filter(s=>s.status==='ended').length}].map(item=><button type="button" className={status===item.value?'active':''} aria-pressed={status===item.value} key={item.value} onClick={()=>setStatus(item.value)}><span>{item.label}</span><strong>{item.count}</strong></button>)}</div><div className="student-toolbar"><label className="search-field"><Search size={18}/><span className="sr-only">Tìm học sinh</span><input type="search" placeholder="Tìm theo tên, lớp hoặc môn học..." aria-label="Tìm học sinh" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="student-list-controls"><label><span className="sr-only">Trạng thái học sinh</span><select aria-label="Trạng thái học sinh" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tất cả trạng thái</option><option value="active">Đang học</option><option value="paused">Tạm nghỉ</option><option value="ended">Đã kết thúc</option></select></label><div className="segmented-control"><button type="button" className={view==='cards'?'active':''} aria-label="Xem dạng thẻ" aria-pressed={view==='cards'} onClick={()=>setView('cards')}><LayoutGrid size={17}/></button><button type="button" className={view==='table'?'active':''} aria-label="Xem dạng bảng" aria-pressed={view==='table'} onClick={()=>setView('table')}><List size={18}/></button></div></div></div>
    {!students.length?<div className="panel"><EmptyState title={data.students.length?'Chưa tìm thấy học sinh phù hợp':'Bắt đầu với học sinh đầu tiên'} description={data.students.length?'Thử một tên khác hoặc điều chỉnh bộ lọc.':'Tạo hồ sơ, nhập học phí và xây dựng lịch học đầu tiên.'} action={data.students.length?<Button onClick={()=>{setQuery('');setStatus('all');}}>Xóa bộ lọc</Button>:<Button variant="primary" onClick={()=>setAdding(true)}><Plus size={16}/>Thêm học sinh</Button>}/></div>:view==='cards'?<div className="students-grid">{students.map(student=>{const next=nextSession(student.id);return <article className="student-card panel" key={student.id}><div className="student-card-heading"><Avatar student={student} size="large"/><StatusBadge status={student.status}/><Button variant="ghost" aria-label={`Chỉnh sửa ${student.name}`} onClick={()=>setEditing(student)}><Pencil size={16}/></Button></div><Link className="student-card-main" to={`/students/${student.id}`}><h2>{student.name}</h2><p>{student.grade} <span>·</span> {student.subject}</p><div className="student-card-data"><span>{student.mode==='online'?<Video size={15}/>:<MapPin size={15}/>} {student.mode==='online'?'Trực tuyến':'Trực tiếp'}</span><span><BookOpen size={15}/>{completedCount(student.id)} buổi đã học</span></div><div className="student-card-rate"><span>Học phí</span><strong>{money(student.rate)}<small>/{student.rateType==='hour'?'giờ':'buổi'}</small></strong></div><div className="student-card-next"><CalendarDays size={16}/><span>{next?`Buổi tiếp theo: ${formatDate(next.date).slice(0,5)} · ${next.startTime}`:'Chưa có lịch học tiếp theo'}</span></div><div className="student-card-link">Xem hồ sơ <ChevronRight size={16}/></div></Link></article>;})}</div>:<div className="panel table-wrap"><table className="data-table"><thead><tr><th>Học sinh</th><th>Môn học / Lớp</th><th>Phụ huynh</th><th>Đơn giá</th><th>Trạng thái</th><th/></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><Link className="student-table-name" to={`/students/${s.id}`}><Avatar student={s}/><strong>{s.name}</strong></Link></td><td>{s.subject}<small className="table-subtext">{s.grade}</small></td><td>{s.parentName||'Chưa cập nhật'}<small className="table-subtext">{s.parentPhone||'—'}</small></td><td>{money(s.rate)}<small className="table-subtext">/{s.rateType==='hour'?'giờ':'buổi'}</small></td><td><StatusBadge status={s.status}/></td><td><Button variant="ghost" onClick={()=>setEditing(s)} aria-label={`Chỉnh sửa ${s.name}`}><Pencil size={16}/></Button></td></tr>)}</tbody></table></div>}
    <StudentForm open={adding||Boolean(editing)} onClose={()=>{setAdding(false);setEditing(undefined);if(requestNew){const next=new URLSearchParams(params);next.delete('new');setParams(next,{replace:true});}}} student={editing}/>{selected&&<StudentDetail student={selected} onClose={()=>navigate('/students')}/ >}{id&&!selected&&<Modal open onClose={()=>navigate('/students')} title="Không tìm thấy học sinh"><EmptyState title="Hồ sơ không tồn tại" description="Hãy quay lại danh sách học sinh để chọn một hồ sơ khác." action={<Button onClick={()=>navigate('/students')}>Về danh sách</Button>}/></Modal>}</>;
}
