import { useEffect, useState, type FormEvent } from 'react';
import { CalendarDays, Clock3, Repeat2, Info } from 'lucide-react';
import { useWorkspace } from '../store';
import { today, newId, money } from '../domain';
import type { TeachingSession, TeachingSchedule, SessionStatus, TeachingMode, WorkspaceData } from '../types';
import { weeklyDates, weekdays, minutesBetween, prepareSessionCandidates, shiftDate, seriesEditableSessions } from '../calendar';
import { Button, Field, Modal, statusLabels } from './ui';
type Values={studentId:string;date:string;startTime:string;endTime:string;subject:string;mode:TeachingMode;location:string;notes:string;status:SessionStatus;actualMinutes:string;billable:string;endDate:string;weekdays:number[];recurring:boolean;scope:'one'|'series'};
export function SessionForm({open,onClose,session,initialDate,initialStudentId}:{open:boolean;onClose:()=>void;session?:TeachingSession;initialDate?:string;initialStudentId?:string}) {
  const {data,update,saving}=useWorkspace(); const [error,setError]=useState('');
  function initial():Values {const student=data.students.find(s=>s.id===(session?.studentId||initialStudentId))||data.students.find(s=>s.status==='active')||data.students[0];const date=session?.date||initialDate||today();const series=data.schedules.find(s=>s.id===session?.scheduleId);return {studentId:student?.id||'',date,startTime:session?.startTime||'18:00',endTime:session?.endTime||'19:30',subject:session?.subject||student?.subject||'',mode:session?.mode||student?.mode||'online',location:session?.location||'',notes:session?.notes||'',status:session?.status||'scheduled',actualMinutes:session?.actualMinutes?.toString()||'',billable:session?.billable===null||session?.billable===undefined?'auto':session.billable?'yes':'no',endDate:series?.endDate||shiftDate(date,90),weekdays:series?.weekdays||[new Date(date+'T12:00:00').getDay()],recurring:false,scope:'one'};}
  const [form,setForm]=useState<Values>(initial);useEffect(()=>{if(open){setForm(initial());setError('');}},[open,session?.id,initialDate,initialStudentId]);
  const change=<K extends keyof Values>(key:K,value:Values[K])=>setForm(f=>({...f,[key]:value})); const student=data.students.find(s=>s.id===form.studentId); const duration=minutesBetween(form.startTime,form.endTime); const isSeries=form.recurring||form.scope==='series';
  function selectStudent(id:string) {const selected=data.students.find(s=>s.id===id);setForm(f=>({...f,studentId:id,subject:selected?.subject||f.subject,mode:selected?.mode||f.mode}));}
  async function submit(e:FormEvent) {
    e.preventDefault();setError(''); if(!student){setError('Hãy chọn một học sinh.');return;}if(!form.subject.trim()){setError('Vui lòng nhập môn học.');return;}if(!(duration>0&&duration<=720)){setError('Giờ kết thúc phải sau giờ bắt đầu, tối đa 12 giờ mỗi buổi.');return;}if(isSeries&&(!form.weekdays.length||form.endDate<form.date||form.endDate>shiftDate(form.date,730))){setError('Chọn ít nhất một thứ và khoảng lặp hợp lệ, tối đa 2 năm.');return;}if(form.actualMinutes&&(!Number.isInteger(Number(form.actualMinutes))||Number(form.actualMinutes)<1||Number(form.actualMinutes)>1440)){setError('Thời lượng thực tế phải từ 1 đến 1.440 phút.');return;}
    let amount=1;
    function transform(d:WorkspaceData):WorkspaceData {
      const currentStudent=d.students.find(s=>s.id===form.studentId);if(!currentStudent)throw new Error('Học sinh không còn tồn tại.');const now=new Date().toISOString();const activeSession=session?d.sessions.find(s=>s.id===session.id):undefined;if(session&&!activeSession)throw new Error('Buổi học không còn tồn tại.');const currentSchedule=d.schedules.find(s=>s.id===session?.scheduleId);const scheduleId=isSeries?(form.scope==='series'&&currentSchedule?currentSchedule.id:newId()):null;const effectiveStart=form.scope==='series'&&form.date<today()?today():form.date;const dates=isSeries?weeklyDates(effectiveStart,form.endDate,form.weekdays):[form.date];if(!dates.length)throw new Error('Khoảng thời gian chưa có ngày nào phù hợp với các thứ đã chọn.');
      if(form.scope==='series'&&currentSchedule&&currentSchedule.studentId!==form.studentId)throw new Error('Không thể thay học sinh cho cả chuỗi. Hãy tạo một lịch mới.');
      const protectedIds=d.invoices.flatMap(i=>i.items.flatMap(item=>item.sessionId?[item.sessionId]:[]));
      const replace= form.scope==='series'&&currentSchedule ? seriesEditableSessions(d.sessions,currentSchedule.id,today(),protectedIds) : activeSession?[activeSession]:[];
      const retained=d.sessions.filter(s=>!replace.some(r=>r.id===s.id));
      const candidates:TeachingSession[]=dates.map(date=>{const prior=form.scope==='series'?replace.find(s=>s.date===date&&s.studentId===form.studentId):activeSession;return {id:prior?.id||newId(),studentId:form.studentId,scheduleId,date,startTime:form.startTime,endTime:form.endTime,subject:form.subject.trim(),mode:form.mode,location:form.location.trim(),notes:form.notes.trim(),status:prior&&prior.date!==date&&form.status==='scheduled'?'rescheduled':form.status,actualMinutes:form.actualMinutes?Number(form.actualMinutes):null,billable:form.billable==='auto'?null:form.billable==='yes',rate:prior?.rate??currentStudent.rate,rateType:prior?.rateType??currentStudent.rateType,lessonNote:prior?.lessonNote||{content:'',attitude:'',understanding:'',homework:'',nextPlan:''},createdAt:prior?.createdAt||now,updatedAt:now};});
      const unique=prepareSessionCandidates(candidates,retained,isSeries);amount=unique.length;
      const schedule:TeachingSchedule={id:scheduleId||'',studentId:form.studentId,weekdays:form.weekdays,startDate:form.date,endDate:form.endDate,startTime:form.startTime,endTime:form.endTime,subject:form.subject.trim(),mode:form.mode,location:form.location.trim(),notes:form.notes.trim(),createdAt:currentSchedule?.createdAt||now,updatedAt:now};
      return {...d,sessions:[...retained,...unique],schedules:isSeries?[...d.schedules.filter(s=>s.id!==schedule.id),schedule]:d.schedules};
    }
    try{transform(data);}catch(e){setError(e instanceof Error?e.message:'Lịch học chưa hợp lệ.');return;}const saved=await update(transform,session?'Đã cập nhật lịch học':`Đã tạo ${amount} buổi học`);if(saved)onClose();else setError('Chưa lưu được lịch. Vui lòng kiểm tra thông báo và thử lại.');
  }
  return <Modal open={open} onClose={onClose} title={session?'Chỉnh sửa lịch dạy':'Thêm lịch dạy'} description="Sắp xếp thời gian, giữ nhịp học đều đặn." wide><form onSubmit={submit}>
    {!data.students.length?<div className="form-hint">Bạn cần thêm học sinh trước khi tạo lịch dạy.</div>:<><div className="form-grid"><Field label="Học sinh *"><select required disabled={form.scope==='series'} value={form.studentId} onChange={e=>selectStudent(e.target.value)}>{data.students.map(s=><option key={s.id} value={s.id}>{s.name}{s.status!=='active'?` · ${s.status==='paused'?'Tạm nghỉ':'Đã kết thúc'}`:''}</option>)}</select></Field><Field label="Môn học *"><input required maxLength={120} value={form.subject} onChange={e=>change('subject',e.target.value)}/></Field>{session?.scheduleId&&<Field label="Phạm vi chỉnh sửa" className="field-full"><select value={form.scope} onChange={e=>{const scope=e.target.value as Values['scope'];const schedule=data.schedules.find(s=>s.id===session.scheduleId);if(scope==='series'&&schedule)setForm(f=>({...f,scope,status:'scheduled',studentId:schedule.studentId,date:schedule.startDate,endDate:schedule.endDate,weekdays:schedule.weekdays,startTime:schedule.startTime,endTime:schedule.endTime}));else change('scope',scope);}}><option value="one">Chỉ buổi học này</option><option value="series">Toàn bộ các buổi tương lai của chuỗi</option></select></Field>}<Field label={isSeries?'Ngày bắt đầu chu kỳ *':'Ngày dạy *'}><input required type="date" value={form.date} onInput={e=>change('date',e.currentTarget.value)} onChange={e=>change('date',e.target.value)}/></Field><Field label="Trạng thái"><select value={form.status} onChange={e=>change('status',e.target.value as SessionStatus)}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Giờ bắt đầu *"><input required type="time" value={form.startTime} onInput={e=>change('startTime',e.currentTarget.value)} onChange={e=>change('startTime',e.target.value)}/></Field><Field label="Giờ kết thúc *"><input required type="time" value={form.endTime} onInput={e=>change('endTime',e.currentTarget.value)} onChange={e=>change('endTime',e.target.value)}/></Field></div><div className="duration-callout"><Clock3 size={17}/><span>Thời lượng dự kiến: <strong>{duration>0?`${Math.floor(duration/60)} giờ${duration%60?` ${duration%60} phút`:''}`:'Chưa hợp lệ'}</strong></span></div>
    {!session&&<label className="checkbox-field"><input type="checkbox" checked={form.recurring} onChange={e=>change('recurring',e.target.checked)}/><Repeat2 size={17}/> Lặp lại hàng tuần</label>}{isSeries&&<div className="recurrence-box"><div className="weekday-picker">{[1,2,3,4,5,6,0].map(day=><button className={form.weekdays.includes(day)?'selected':''} key={day} type="button" aria-pressed={form.weekdays.includes(day)} onClick={()=>change('weekdays',form.weekdays.includes(day)?form.weekdays.filter(d=>d!==day):[...form.weekdays,day])}>{weekdays[day]}</button>)}</div><Field label="Ngày kết thúc chu kỳ *"><input required type="date" min={form.date} max={shiftDate(form.date,730)} value={form.endDate} onInput={e=>change('endDate',e.currentTarget.value)} onChange={e=>change('endDate',e.target.value)}/></Field><p className="muted"><CalendarDays size={14}/> {weeklyDates(form.scope==='series'&&form.date<today()?today():form.date,form.endDate,form.weekdays).length} buổi dự kiến. Các buổi đã có của học sinh này sẽ được bỏ qua.</p>{form.scope==='series'&&<p className="form-hint">Chỉ cập nhật các buổi từ hôm nay chưa hoàn thành. Toàn bộ lịch sử và các buổi đã hoàn thành được giữ lại.</p>}</div>}
    <div className="form-grid"><Field label="Hình thức"><select value={form.mode} onChange={e=>change('mode',e.target.value as TeachingMode)}><option value="online">Trực tuyến</option><option value="offline">Trực tiếp</option></select></Field><Field label={form.mode==='online'?'Link học (tùy chọn)':'Địa điểm (tùy chọn)'}><input maxLength={1000} placeholder={form.mode==='online'?'https://meet.google.com/...':'Địa chỉ buổi học'} value={form.location} onChange={e=>change('location',e.target.value)}/></Field>{form.status==='completed'&&<Field label="Thời lượng thực tế (phút)" hint="Bỏ trống để dùng thời lượng dự kiến."><input type="number" min={1} max={1440} step={1} value={form.actualMinutes} onChange={e=>change('actualMinutes',e.target.value)}/></Field>}<Field label="Tính học phí" hint="Tự động: chỉ tính các buổi đã hoàn thành."><select value={form.billable} onChange={e=>change('billable',e.target.value)}><option value="auto">Tự động theo trạng thái</option><option value="yes">Có tính phí</option><option value="no">Không tính phí</option></select></Field><Field label="Ghi chú lịch dạy" className="field-full"><textarea rows={3} maxLength={10000} value={form.notes} onChange={e=>change('notes',e.target.value)}/></Field></div><p className="form-hint"><Info size={15}/> Đơn giá buổi học: {money(session?.rate??student?.rate??0)}/{(session?.rateType??student?.rateType)==='hour'?'giờ':'buổi'}. Được lưu riêng tại thời điểm tạo lịch.</p></>}
    {error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><Button type="button" onClick={onClose}>Hủy</Button><Button type="submit" variant="primary" disabled={!data.students.length} loading={saving}>{session?'Lưu thay đổi':isSeries?'Tạo lịch lặp lại':'Tạo buổi học'}</Button></div></form></Modal>;
}
export default SessionForm;
