import { describe, expect, it } from 'vitest';
import { cancelSessionScope, sameSlot, seriesEditableSessions, sessionAlreadyRetained, shiftDate, validateSessionConflicts, weeklyDates } from './calendar';
import type { TeachingSession } from './types';
const session=(overrides:Partial<TeachingSession>={}):TeachingSession=>({id:'lesson-1',studentId:'student-1',scheduleId:'series-1',date:'2026-10-01',startTime:'18:00',endTime:'19:30',subject:'Toán',mode:'online',location:'',notes:'',status:'scheduled',actualMinutes:null,billable:null,rate:150000,rateType:'hour',lessonNote:{content:'',attitude:'',understanding:'',homework:'',nextPlan:''},createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z',...overrides});
describe('Lịch lặp lại và bảo toàn lịch sử',()=>{
  it('sinh đúng các thứ trong khoảng, bao gồm hai đầu',()=>{expect(weeklyDates('2026-10-01','2026-10-15',[1,4])).toEqual(['2026-10-01','2026-10-05','2026-10-08','2026-10-12','2026-10-15']);});
  it('xử lý ranh giới tháng và năm nhuận',()=>{expect(shiftDate('2028-02-28',1)).toBe('2028-02-29');expect(shiftDate('2026-12-31',1)).toBe('2027-01-01');expect(weeklyDates('2026-10-02','2026-10-01',[4])).toEqual([]);expect(weeklyDates('2026-10-01','2026-10-31',[])).toEqual([]);});
  it('ngăn giáo viên trùng giờ giữa hai học sinh',()=>{expect(()=>validateSessionConflicts([session({id:'lesson-2',studentId:'student-2',startTime:'19:00',endTime:'20:00'})],[session()])).toThrow('Trùng lịch');});
  it('cho phép hai buổi nối tiếp và chỉnh sửa giữ nguyên ID',()=>{expect(()=>validateSessionConflicts([session({id:'lesson-2',startTime:'19:30',endTime:'20:30'})],[session()])).not.toThrow();expect(()=>validateSessionConflicts([session()],[session()])).not.toThrow();});
  it('không chiếm giờ của buổi đã hủy hoặc xin nghỉ',()=>{expect(()=>validateSessionConflicts([session({id:'lesson-2'})],[session({status:'cancelled'}),session({id:'lesson-3',status:'student_absent'})])).not.toThrow();});
  it('ngăn các buổi mới trong cùng thao tác trùng nhau',()=>{expect(()=>validateSessionConflicts([session(),session({id:'lesson-2',studentId:'student-2'})],[])).toThrow('Trùng lịch');});
  it('nhận biết buổi trùng dù thuộc chuỗi khác',()=>{expect(sameSlot(session(),session({id:'lesson-2',scheduleId:'series-2'}))).toBe(true);expect(sameSlot(session(),session({studentId:'student-2'}))).toBe(false);});
  it('hủy toàn chuỗi giữ nguyên lịch sử và buổi hoàn thành',()=>{const rows=[session({id:'past',date:'2026-09-30',status:'completed'}),session({id:'done',date:'2026-10-02',status:'completed'}),session({id:'future',date:'2026-10-03'}),session({id:'different',date:'2026-10-03',scheduleId:'series-2'})];const result=cancelSessionScope(rows,'past',true,'2026-10-01');expect(result[0]).toEqual(rows[0]);expect(result[1]).toEqual(rows[1]);expect(result[2].status).toBe('cancelled');expect(result[2].billable).toBe(false);expect(result[3]).toEqual(rows[3]);});
  it('chỉnh chuỗi giữ nguyên buổi đã lập hóa đơn và các bản ghi lịch sử',()=>{const rows=[session({id:'past',date:'2026-09-30'}),session({id:'done',status:'completed'}),session({id:'billed'}),session({id:'future',date:'2026-10-03'})];expect(seriesEditableSessions(rows,'series-1','2026-10-01',['billed']).map(s=>s.id)).toEqual(['future']);});
  it('đổi giờ cả chuỗi không tạo thêm buổi ở ngày có lịch sử được bảo toàn',()=>{const completed=session({status:'completed'});const candidate=session({id:'new',startTime:'20:00',endTime:'21:00'});expect(sessionAlreadyRetained(candidate,[completed])).toBe(true);expect(sessionAlreadyRetained({...candidate,date:'2026-10-02'},[completed])).toBe(false);expect(sessionAlreadyRetained({...candidate,scheduleId:'series-2'},[completed])).toBe(false);});
});
